In [1]:
import torch
#from matplotlib import pyplot as plt
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
import cv2

In [2]:
model = torch.hub.load('ultralytics/yolov5', 'custom', path='D:\\best.pt', force_reload=True)

Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\rahee/.cache\torch\hub\master.zip
YOLOv5  2022-10-27 Python-3.10.4 torch-1.12.1+cpu CPU

Fusing layers... 
custom_model summary: 213 layers, 7018216 parameters, 0 gradients, 15.8 GFLOPs
Adding AutoShape... 


In [ ]:
cap = cv2.VideoCapture(0)


while cap.isOpened():
    ret, frame = cap.read()

    # Make detections 
    results = model(frame)
    results.xyxy[0]  # im predictions (tensor)
    dat=results.pandas().xyxy[0]  # im predictions (pandas)
    name=dat[["name"]]
    output=name.values
    
    con=dat[["confidence"]]
    conout=con.values
    for (i,lab) in enumerate(conout):
        confid=conout
        confid=confid*100
        print(confid)
        
    
    
    for (i,lab) in enumerate(output):
        if (confid >=30).any():  # accuracy change it accoding to your thersuld 
            if lab == 'Healthy-plant':
                print("use here pyserial for arduino")
            if lab=="Late-Blight":
                print("copy same for next class ")
    
    cv2.imshow('YOLO', np.squeeze(results.render()))
    
    
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
    

[[     28.816]
 [     26.552]]
[[     28.816]
 [     26.552]]
[[     28.154]]
[[     31.703]
 [     27.203]]
[[     31.703]
 [     27.203]]
raheem
project
[[     27.243]]
[[     37.395]]
raheem
[[     29.023]]
